version: 0.2
phases:
  pre_build:
    commands:
      - git show --name-status HEAD
      - echo logging into ecr...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo building image for $CODEBUILD_SOURCE_VERSION...
      - docker build -t websocket-service .
      - docker tag websocket-service $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$(git rev-parse HEAD)
      - echo smoke testing image...
      - docker run --rm websocket-service --help
  post_build:
    commands:
      - echo pushing image...
      - docker push $ECR_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ECR_REPO_NAME:$(git rev-parse HEAD)
